spring:
  application:
    name: campaign-manager
    
  datasource:
    url: jdbc:postgresql://localhost:5432/campaignmanager
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true
    open-in-view: false
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-change-in-production-this-is-just-for-development-and-testing-purposes-only}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
      
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:}
    region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  
logging:
  level:
    root: INFO
    com.portfolio.campaignmanager: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/campaign-manager.log
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always